### ISSUE TITLE
Could not install package 'CCXT.NET 1.0.0'

### ISSUE THREAD

**Issue by Ch-301** [lisa3907/ccxt.net#1]
The package 'CCXT.NET 1.0.0' can not be installed.Why?
Error		
Could not install package 'CCXT.NET 1.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by lisa3907** [comment]
CCXT.NET use .net-framework 4.6.2 or higher.
