### ISSUE TITLE
Bitstamp Sample example is missed , OdinSdk.BaseLib DLL doesn't exist for .Net Core

### ISSUE THREAD

**Issue by mitnick2012** [lisa3907/ccxt.net#10]
hello , I'm  struggling with the implementation of Bit stamp buy and sell API functions it doesn't work for me because I m working in .Net core environment and the version of this dll is .Net Framework 
can you please help me with that.
thanks in advance

**Comment by lisa3907** [comment]
ccxt.net is a netstandard DLL, so there is no problem using it with .net core.

**Comment by mitnick2012** [comment]
hello thanks for replay, I tried to download the OdinSdk.BaseLib nugget inside a .Net core project but it doesn't work, and also if you can provide bitstamp simple example to do trading ( buy and sell) operations using this code.
thanks

**Comment by lisa3907** [comment]
retry this
```
Install-Package OdinSdk.BaseLib -Version 2.2.3
```
