### ISSUE TITLE
FetchOHLCVs errors since update

### ISSUE THREAD

**Issue by Retcorp** [lisa3907/ccxt.net#13]
Not sure if this is the appropriate place to post, or if it should be in CCXT, or the Odinsoft library.

I've had CCXT.Net working perfectly in c# until I mistakenly hit "Update all Nuget packages" yesterday. Things seem to have gone a little awry. "FetchOHLCVs" on the public api for example appears to have now completely disappeared to be replaced with "FetchOHLCVsAsync" as the only option which in return gives me a  "Not Supported" error. I've switched packages back and forward in version (OdinSoft and CCXT.Net) to try and get things working as they were, but cannot get a version of Fetching OHLCVs to work again (I've had the old one working for 4 months without issue). I've broken it down to a simple 2 lines now for testing purposes (I had it doing reflection to create objects from config files previously). Basically, I want to call for OHLCVs on the Kraken exchange. Any thoughts on why it's not working any more and what my approach should be...

```
var kPublic = new CCXT.NET.Kraken.Public.PublicApi();
var OHLCVs = await kPublic.FetchOHLCVs(BaseAsset, QuoteAsset, timeframe, Since, MaxCount);
```

gives me a "Method not found" at runtime (but not at design time)

```
var kPublic = new CCXT.NET.Kraken.Public.PublicApi();
var OHLCVs = await kPublic.FetchOHLCVsAsync(BaseAsset, QuoteAsset, timeframe, Since, MaxCount);
```

gives me a "Not supported" error code.

What has changed to make this suddenly appear incompatible? I have the following versions:
CCXT.Net: 1.3.6
OdinSdk.BaseLib: 2.2.8 (I noticed that this seems to have been changed more recently)

**Comment by lisa3907** [comment]
The error has been fixed. You can check it out here: https://github.com/lisa3907/ccxt.net/tree/master/sample/kraken.

**Comment by lisa3907** [comment]
The error has been fixed. You can check it out here: https://github.com/lisa3907/ccxt.net/tree/master/sample/kraken.

CCXT.NET: v1.3.7
OdinSdk.BaseLib: Not used
Please refer to https://github.com/lisa3907/ccxt.net/releases/tag/v1.3.7
