### ISSUE TITLE
Phemex Exchange

### ISSUE THREAD

**Issue by ghost** [lisa3907/ccxt.net#14]
Any plans to inlcude the phemex exchange soon or in progress allready?

**Comment by lisa3907** [comment]
Not right now, but let's try.

**Comment by lisa3907** [comment]
Not right now, but let's try.

**Comment by lisa3907** [comment]
phemex가 어느 나라 거래소 인가요? 다른 거래소 보다 중요한 거래소 이면 먼저 추가 하겠습니다.
