### ISSUE TITLE
What methods are supported

### ISSUE THREAD

**Issue by ondrejnovotny** [lisa3907/ccxt.net#16]
Hi, I've tried getting ticker on multiple pairs and still getting ""not supoorted yet". 

I mean like:
 
`var ticker = await _public_api.FetchTickerAsync("btc", "usd");`

but in markets I can see this pair. In what state i currently this library? Tickers are not implemented as I see in code?

**Comment by lisa3907** [comment]
Do you mean on the binance exchange?

**Comment by lisa3907** [comment]
try below code 
```
var _tickers = await _public_api.FetchTickersAsync();
var _btcusd_tickers = _tickers.result.Where(t => t.symbol.ToUpper().Contains("BTCUSD"));

```

**Comment by ondrejnovotny** [comment]
Yeah I mean Binance, Kraken etc.  FetchTickerAsync is not implemented? I can contribute but I need to now what is supposed to be supported and implemented.

**Comment by lisa3907** [comment]
> Yeah I mean Binance, Kraken etc. FetchTickerAsync is not implemented? I can contribute but I need to now what is supposed to be supported and implemented.

You can implement it like the sample above

**Comment by ondrejnovotny** [comment]
Well, those results are not what you expect..

Currently:

on Kraken - No results

on Binance - Three results without price (zero everywhere)

**Comment by lisa3907** [comment]
![image](https://user-images.githubusercontent.com/3665952/99362697-2653ee80-28f7-11eb-94eb-6b4b6ba6f4ee.png)

**Comment by lisa3907** [comment]
![image](https://user-images.githubusercontent.com/3665952/99362801-44215380-28f7-11eb-8b9c-ce7bfb65b070.png)

**Comment by ondrejnovotny** [comment]
Running from cloned repo..

Kraken 
![image](https://user-images.githubusercontent.com/36995404/99369464-bf194880-28bc-11eb-876d-a2d0692bf823.png)

Binance
![image](https://user-images.githubusercontent.com/36995404/99369668-01db2080-28bd-11eb-9868-5d92bb2aa6fb.png)

**Comment by lisa3907** [comment]
What is your windows system's language?

**Comment by ondrejnovotny** [comment]
Why is this an issue? App should work on any region settings.

![image](https://user-images.githubusercontent.com/36995404/99371586-60090300-28bf-11eb-8f97-863958f149b3.png)
![image](https://user-images.githubusercontent.com/36995404/99371625-71eaa600-28bf-11eb-9f3b-d033835153d8.png)

**Comment by lisa3907** [comment]
After git pull this repository, Capture here like below image.

![image](https://user-images.githubusercontent.com/3665952/99372493-97999e80-2903-11eb-8b0b-4678aacd9d14.png)

**Comment by ondrejnovotny** [comment]
It works now

![image](https://user-images.githubusercontent.com/36995404/99374349-c5aabe80-28c2-11eb-9e12-2765a8b789a8.png)

**Comment by lisa3907** [comment]
Did you solving your problem? May I close this issue?

**Comment by ondrejnovotny** [comment]
Yes thanks. I don't quite know how but it's ok. Thanks

And I can see now that I shoud use for example FetchTickerAsync("BTC", "USD**T**") instead od  FetchTickerAsync("BTC", "USD")

**Comment by lisa3907** [comment]
FetchTickerAsync("BTC", "USDT") is not supporting. 
I will close this issue.
