### ISSUE TITLE
Is order placement supported?

### ISSUE THREAD

**Issue by quantitative-technologies** [lisa3907/ccxt.net#17]
I was just looking through the code, and it looks like the CreateOrder functions are not implemented yet.

Is it correct, that this library cannot yet be used to place orders?

**Comment by lisa3907** [comment]
You can use TradeAPI's CreateLimitOrderAsync.

**Comment by quantitative-technologies** [comment]
I don't understand? On Line 502-503 of tradeApi.cs we have:

     _result.SetFailure("not supported yet", ErrorCode.NotSupported);
     _result.supported = false;

It looks like `CreateLimitOrderAsync` is not supported yet.

**Comment by lisa3907** [comment]
You are misunderstanding. cheer up

**Comment by quantitative-technologies** [comment]
Yes, I am happy to hear that. 

I have made a [pull request]( https://github.com/ccxt-net/ccxt.net/pull/18 ) with an order placement example in bitmex, in case that is helpful.
