### ISSUE TITLE
Any plan on supporting FTX and Kucoin exchanges?

### ISSUE THREAD

**Issue by dobrado76** [lisa3907/ccxt.net#19]
Both exchanges are well known and are supported by CCXT (Python and Javascript) library but not CCXT.Net.

Is there any plan to support them?

**Comment by Amannda123** [comment]
same question here :)

**Comment by lisa3907** [comment]
kucoin은 어느 나라 거래소 인가요? 다른 거래소 보다 중요한 거래소 이면 먼저 추가 하겠습니다.

**Comment by lisa3907** [comment]
has been imlemented in https://github.com/ccxt-net/ccxt.simple.
so close this issue
