### ISSUE TITLE
Bittrex 1.1 Api past end of life. 

### ISSUE THREAD

**Issue by pjobling999** [lisa3907/ccxt.net#21]
HI I am having an issue creating orders on Bittrex and I noticed you are still using version 1.1 of Bittrex API. Bittrex say this needs to be upgraded to version 3 so I wondered if you had any plans to do this?

Issue seems to be with TradeApi CreateLimitOrder

Thanks!

**Comment by lisa3907** [comment]
I will upgrade asap.

**Comment by lisa3907** [comment]
Fixed an error in which there was a problem with the operation due to the need for time to upgrade.
