### ISSUE TITLE
ccxt.net-1.3.7\sample\binance request timed-out.

### ISSUE THREAD

**Issue by forconz** [lisa3907/ccxt.net#22]
![20210225184857](https://user-images.githubusercontent.com/9990289/109142711-27b87100-779a-11eb-9224-3ecdc3493f4c.png)

**Comment by lisa3907** [comment]
![image](https://user-images.githubusercontent.com/3665952/109205405-e18afe00-77e9-11eb-8dc6-b60ccc7186ce.png)
