### ISSUE TITLE
The request timed-out.

### ISSUE THREAD

**Issue by zengxiuhao** [lisa3907/ccxt.net#27]
run  binance  sample . i'm in china.

request timeout: 0/3, /exchangeInfo
request timeout: 1/3, /exchangeInfo
request timeout: 2/3, /exchangeInfo

**Comment by lisa3907** [comment]
What's wrong? No errors were found.

**Comment by zengxiuhao** [comment]
the bittrex  sample can work .
but huobi , okex, binance, don't work.
i think because of my ip adress .
my ip address is in china . 
the  Exchange Markets  Prohibit Internet access in Mainland China。
thanks you .
maybe i need Rent a foreign cloud server。
