### ISSUE TITLE
Forking this project, I'm not seeing many objects that are part of the Nuget package

### ISSUE THREAD

**Issue by rhartness** [lisa3907/ccxt.net#3]
I've written a simplistic trading tool using the Nuget package linked within this application.  I need to make some minor additions for my own needs, so I forked and pulled down the project. I'm sure this isn't an exhausted list but I can't find project members like `IPublicOrder` or `PublicTicker`.  Specifically, these are within the Poloniex library.

Is a part of this project source missing from this repo, that's built into the Nuget package?

**Comment by lisa3907** [comment]
Poloniex's PublicOrder is CCXT.NET.Poloniex.Public.PTradeItem and PublickTicker is CCXT.NET.Poloniex.Public.PTickerItem.

**Comment by rhartness** [comment]
Thank you for responding.  I'll update my code.  Was this a code change that's not propagated to the nuget package?  I'm curious why there's a difference.  Again, thanks, especially for the quick response.

**Comment by lisa3907** [comment]
I just uploaded it to Nuget.
