### ISSUE TITLE
Where can I find corresponding CreateAddressAsync function in JavaScript.

### ISSUE THREAD

**Issue by zydjohnHotmail** [lisa3907/ccxt.net#33]
Hello:
I used CCXT JavaScript for a while, but I have issue to for FetchAddress on its JavaScript for exchange Poloniex.
I looked at ccxt.net source code, and I found there is one statement like this:
var _new_address = await _private_api.CreateAddressAsync("XRP", GetJsonContent(_private_api.privateClient, "createAddress", _args));
But I can't find the corresponding function in JavaScript.
Let me know if I have to use this function before I can use FetchAddressAsync, or this is the only exception for exchange: Poloniex.
I am using Windows 10 (21H2), and nuget package CCXT.NET version 1.4.13.
Please advise,
Thanks,

**Comment by lisa3907** [comment]
Using fetchaddress means that you have run createaddress in the past.
