### ISSUE TITLE
Are there any plans to support websocket

### ISSUE THREAD

**Issue by yuxi214** [lisa3907/ccxt.net#6]
Are there any plans to support websocket

**Comment by lisa3907** [comment]
I have a plan, what do you want exchange.

**Comment by Tollervey** [comment]
Signal R is a good tech to use.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by wil70** [comment]
Any plan to add websocket support for all those exchanges? Binance, Bitmex, coinbase, bitfinex, bitrex....
thanks!

**Comment by lisa3907** [comment]
Review the https://github.com/ccxt-net/ccxt.collector project to see if it's what you want
