### ISSUE TITLE
Basic Documentation needed

### ISSUE THREAD

**Issue by AndreaDev3D** [lisa3907/ccxt.net#7]
Can we have at least basic documentation, please?

**Comment by lisa3907** [comment]
I will write if I can afford it, but is there anyone who can help me?

**Comment by AndreaDev3D** [comment]
Are you asking for help or for money?
I can help to fill the wike with some examples but I need to know what is the basic usage for at least 1 exchange.

**Comment by lisa3907** [comment]
No!! 
I do not want money.

I belong to another job. I am not a person dedicated to this work (ccxt.net).

**Comment by lisa3907** [comment]
https://github.com/lisa3907/ccxt.net/tree/master/sample/ccxt.test

Please use the sample.

**Comment by oalansilva** [comment]
The example not show

**Comment by lisa3907** [comment]
> The example not show

https://github.com/lisa3907/ccxt.net/tree/master/sample
