### ISSUE TITLE
좋은 라이브러리 감사 드립니다

### ISSUE THREAD

**Issue by gandol2** [lisa3907/ccxt.net#8]
예전에 clone받아서 살짝 테스트만 해보고 손놓고 있었는데 watch를 해두었더니 issues들에 대한 메일이 와서 들어와봤습니다. 
한국분 이신것 같은데 제가 혹시 도와드릴 일은 없을까요?
라이브러리를 더 깊게 알려면 프로젝트에 참여하는것도 하나의 도움이 될것 같아서요.

**Comment by lisa3907** [comment]
그러면 감사하죠^^ 제가 혼자 하기에는 벅찬 부분이 있어서 메뉴얼이랑 튜토리얼등등 만들어야 되는데 못하고 있습니다.

**Comment by gandol2** [comment]
초대 감사합니다. 거래소 라이브러리로 만들어보고싶은게 있어서 개인적인 프로젝트를 진행중에 있었습니다. 본업이 바빠져 잠시 손을 놓고있었는데 이렇게 소통하며 작업을 도와드리다보면 저에게도 조금더 도움이 되지 않을까 해서 요청 드렸습니다. 
톡이나 텔레그램으로 소통할수 있을까요?

**Comment by lisa3907** [comment]
lisa@odinsoftware.co.kr로 메일 주세요
