### ISSUE TITLE
Netcoreapp 2.2 Compatibility

### ISSUE THREAD

**Issue by aliesenli** [lisa3907/ccxt.net#9]
This Library isn't compatible with Netcoreapp2.2 therefore I can't download it to my Project. Is there a way solve this problem?

**Comment by lisa3907** [comment]
After downloading the ccxt.net source, modify the target framework of the project to netstandard 2.0 and try again.

**Comment by AliEsenli** [comment]
Alright. But I've never added a framework manually to the Project without using nuget. Is there a documentation/resource you can recommend me?

**Comment by aliesenli** [comment]
> After downloading the ccxt.net source, modify the target framework of the project to netstandard 2.0 and try again.

Alright. But I've never added a framework manually to the Project without using nuget. Is there a documentation/resource you can recommend me?

**Comment by lisa3907** [comment]
C # program developer right? Attach your source and I'll review it.

**Comment by aliesenli** [comment]
> C # program developer right? Attach your source and I'll review it.

Well it's an ASP.NET Core-Webapplication using MVC pattern. I haven't done anything yet that's why I don't want to attach.

But If you know how to add this framework to an asp.net core-webapplication without using nuget packet manager, I would be thankful.

**Comment by lisa3907** [comment]
![1](https://user-images.githubusercontent.com/3665952/61761668-59bd6080-ae0a-11e9-8f26-767c98434f37.png)
=> ccxt.net solution 

![2](https://user-images.githubusercontent.com/3665952/61761672-5cb85100-ae0a-11e9-8ae9-8a984ba804a9.png)
=> ccxt.net target framework

![3](https://user-images.githubusercontent.com/3665952/61761675-5f1aab00-ae0a-11e9-9dc7-2a9983af6f52.png)
=> ccxt.test target framework

** "프로젝트" is project
** Tester project's name is ccxt.test
